# Chart.yaml
# Production-grade Helm chart metadata with pinned dependencies
# Last updated: 2026-01-03
# Maintainer: Consonant Team <support@consonant.xyz>

apiVersion: v2
name: consonant-relayer
description: |
  Consonant relayer system
  
  Features:
  - Automatic cluster registration
  - Secure tunnel integration (Cloudflare)
  - External secrets support (Vault, AWS, Azure, GCP)
  - Production-ready security controls
  - High availability configuration
  - Network isolation policies
  - Comprehensive observability

type: application
version: 1.0.0
appVersion: "1.0.0"

# Kubernetes version constraints
kubeVersion: ">=1.33.0-0 <1.36.0-0"

# Keywords for discoverability
keywords:
  - ai
  - agents
  - orchestration
  - kubernetes
  - observability
  - telemetry
  - multi-agent
  - control-plane
  - kagent
  - cloudflare
  - enterprise

# Chart maintainers
maintainers:
  - name: Consonant Team
    email: support@consonant.xyz
    url: https://consonant.xyz
  - name: Platform Engineering
    email: platform@consonant.xyz

# Home and source URLs
home: https://consonant.xyz
sources:
  - https://github.com/consonant/consonant
  - https://github.com/consonant/helm-charts

# Chart dependencies with PINNED versions
dependencies:
  # KAgent CRDs - EXACT version pinning
  - name: kagent-crds
    version: "0.7.7"  # ✅ FIXED: Exact version, not 0.7.x
    repository: "oci://ghcr.io/kagent-dev/kagent/helm"
    condition: kagent.installCRDs
    import-values:
      - child: metadata
        parent: kagent.crds
    tags:
      - kagent
      - crds
  
  # KAgent controller - EXACT version pinning
  - name: kagent
    version: "0.7.7"  # ✅ FIXED: Exact version, not 0.7.x
    repository: "oci://ghcr.io/kagent-dev/kagent/helm"
    condition: kagent.enabled
    import-values:
      - child: config
        parent: kagent.config
    tags:
      - kagent

# Annotations for Artifact Hub and Helm Hub
annotations:
  # Category
  category: "AI/ML"
  
  # Licenses
  licenses: "Apache-2.0"
  
  # Artifact Hub specific
  artifacthub.io/category: "ai-ml"
  artifacthub.io/operator: "false"
  artifacthub.io/prerelease: "false"
  artifacthub.io/containsSecurityUpdates: "true"
  artifacthub.io/signKey: |
    fingerprint: 1234567890ABCDEF1234567890ABCDEF12345678
    url: https://keys.consonant.xyz/pgp-key.asc
  
  # Images with DIGESTS (not tags)
  artifacthub.io/images: |
    - name: consonant-relayer
      image: ghcr.io/consonant/relayer@sha256:abc123...
    - name: cloudflared
      image: cloudflare/cloudflared@sha256:def456...
    - name: kubectl
      image: bitnami/kubectl@sha256:789ghi...
  
  # Links
  artifacthub.io/links: |
    - name: Documentation
      url: https://docs.consonant.xyz
    - name: GitHub
      url: https://github.com/consonant/consonant
    - name: Support
      url: https://consonant.xyz/support
    - name: Slack Community
      url: https://consonant.xyz/slack
  
  # Maintainers with GitHub profiles
  artifacthub.io/maintainers: |
    - name: Consonant Team
      email: support@consonant.xyz
  
  # Changelog
  artifacthub.io/changes: |
    - kind: security
      description: Fixed RBAC permissions to prevent secret manipulation
    - kind: security
      description: Added NetworkPolicy egress restrictions
    - kind: security
      description: Pinned all image digests (not tags)
    - kind: added
      description: External secrets support (enabled by default)
    - kind: added
      description: PodDisruptionBudget for high availability
    - kind: added
      description: ServiceMonitor for Prometheus integration
    - kind: added
      description: Comprehensive input validation
    - kind: added
      description: Circuit breaker for backend connections
    - kind: added
      description: Exponential backoff retry logic
    - kind: changed
      description: Init containers use pinned images with timeouts
    - kind: changed
      description: Lifecycle hooks fail pod on backend unreachable
    - kind: fixed
      description: Pre-install hook validates JSON responses
    - kind: fixed
      description: URL and token format validation
  
  # Recommendations
  artifacthub.io/recommendations: |
    - url: https://artifacthub.io/packages/helm/external-secrets-operator/external-secrets
    - url: https://artifacthub.io/packages/helm/prometheus-community/kube-prometheus-stack
  
  # Screenshots
  artifacthub.io/screenshots: |
    - title: Dashboard Overview
      url: https://consonant.xyz/screenshots/dashboard.png
    - title: Agent Telemetry
      url: https://consonant.xyz/screenshots/telemetry.png

# Icon for chart
icon: https://consonant.xyz/logo.svg

# Deprecated flag (false for active charts)
deprecated: false

# Engine constraint
engine: gotpl