{{/*
External Secrets - Integration with External Secrets Operator
=============================================================
Creates ExternalSecret resources that sync from external vaults
Requires External Secrets Operator to be pre-installed
*/}}

{{- if and (eq .Values.secrets.mode "external") .Values.secrets.external.enabled }}

{{/*
=============================================
VALIDATE SECRETSTORE EXISTS (OPTIONAL)
=============================================
*/}}
{{- if .Values.secrets.external.secretStore.validate }}
---
# Pre-install hook to validate SecretStore
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "consonant-relayer.fullname" . }}-validate-secretstore
  namespace: {{ include "consonant-relayer.namespace" . }}
  labels:
    {{- include "consonant-relayer.labels" . | nindent 4 }}
    app.kubernetes.io/component: validation
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-25"
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
spec:
  ttlSecondsAfterFinished: 300
  backoffLimit: 1
  template:
    metadata:
      labels:
        {{- include "consonant-relayer.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: validation
    spec:
      restartPolicy: Never
      serviceAccountName: {{ include "consonant-relayer.fullname" . }}-hook
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        fsGroup: 65534
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: validate
        image: {{ include "consonant-relayer.kubectlImage" . }}
        imagePullPolicy: {{ .Values.hooks.registration.kubectlImage.pullPolicy }}
        command:
          - sh
          - -c
          - |
            set -e
            echo "🔍 Validating SecretStore configuration..."
            
            STORE_NAME="{{ .Values.secrets.external.secretStore.name }}"
            STORE_KIND="{{ .Values.secrets.external.secretStore.kind }}"
            
            if [ "$STORE_KIND" = "ClusterSecretStore" ]; then
              echo "   Checking ClusterSecretStore: $STORE_NAME"
              if kubectl get clustersecretstore "$STORE_NAME" &>/dev/null; then
                echo "✅ ClusterSecretStore '$STORE_NAME' exists"
                exit 0
              else
                echo "❌ ERROR: ClusterSecretStore '$STORE_NAME' not found"
                echo ""
                echo "Please create the ClusterSecretStore first:"
                echo "  kubectl get clustersecretstores"
                echo ""
                echo "Or disable validation:"
                echo "  --set secrets.external.secretStore.validate=false"
                exit 1
              fi
            else
              echo "   Checking SecretStore: $STORE_NAME in namespace {{ include "consonant-relayer.namespace" . }}"
              if kubectl get secretstore "$STORE_NAME" -n {{ include "consonant-relayer.namespace" . }} &>/dev/null; then
                echo "✅ SecretStore '$STORE_NAME' exists"
                exit 0
              else
                echo "❌ ERROR: SecretStore '$STORE_NAME' not found in namespace {{ include "consonant-relayer.namespace" . }}"
                echo ""
                echo "Please create the SecretStore first:"
                echo "  kubectl get secretstores -n {{ include "consonant-relayer.namespace" . }}"
                echo ""
                echo "Or disable validation:"
                echo "  --set secrets.external.secretStore.validate=false"
                exit 1
              fi
            fi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: [ALL]
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 65534
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi
        volumeMounts:
        - name: tmp
          mountPath: /tmp
      volumes:
      - name: tmp
        emptyDir: {}
{{- end }}

{{/*
=============================================
LLM API KEY EXTERNAL SECRET
=============================================
*/}}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "consonant-relayer.llmSecretName" . }}
  namespace: {{ include "consonant-relayer.namespace" . }}
  labels:
    {{- include "consonant-relayer.labels" . | nindent 4 }}
    app.kubernetes.io/component: external-secrets
  {{- with (include "consonant-relayer.annotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
spec:
  # Refresh interval
  refreshInterval: {{ .Values.secrets.external.refreshInterval }}
  
  # SecretStore reference
  secretStoreRef:
    name: {{ .Values.secrets.external.secretStore.name }}
    kind: {{ .Values.secrets.external.secretStore.kind }}
  
  # Target secret to create
  target:
    name: {{ include "consonant-relayer.llmSecretName" . }}
    creationPolicy: Owner
    deletionPolicy: Retain
  
  # Data to fetch
  data:
  - secretKey: apiKey
    remoteRef:
      key: {{ required "secrets.external.paths.llmApiKey.key required" .Values.secrets.external.paths.llmApiKey.key }}
      {{- if .Values.secrets.external.paths.llmApiKey.property }}
      property: {{ .Values.secrets.external.paths.llmApiKey.property }}
      {{- end }}
  
  {{- if eq .Values.llm.provider "azureopenai" }}
  - secretKey: endpoint
    remoteRef:
      key: {{ .Values.secrets.external.paths.azureEndpoint.key }}
      {{- if .Values.secrets.external.paths.azureEndpoint.property }}
      property: {{ .Values.secrets.external.paths.azureEndpoint.property }}
      {{- end }}
  
  - secretKey: deploymentName
    remoteRef:
      key: {{ .Values.secrets.external.paths.azureDeployment.key }}
      {{- if .Values.secrets.external.paths.azureDeployment.property }}
      property: {{ .Values.secrets.external.paths.azureDeployment.property }}
      {{- end }}
  {{- end }}

{{- if .Values.cloudflare.enabled }}
{{/*
=============================================
CLOUDFLARE TUNNEL TOKEN EXTERNAL SECRET
=============================================
*/}}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "consonant-relayer.tunnelSecretName" . }}
  namespace: {{ include "consonant-relayer.namespace" . }}
  labels:
    {{- include "consonant-relayer.labels" . | nindent 4 }}
    app.kubernetes.io/component: external-secrets
  {{- with (include "consonant-relayer.annotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
spec:
  refreshInterval: {{ .Values.secrets.external.refreshInterval }}
  
  secretStoreRef:
    name: {{ .Values.secrets.external.secretStore.name }}
    kind: {{ .Values.secrets.external.secretStore.kind }}
  
  target:
    name: {{ include "consonant-relayer.tunnelSecretName" . }}
    creationPolicy: Owner
    deletionPolicy: Retain
  
  data:
  - secretKey: token
    remoteRef:
      key: {{ required "secrets.external.paths.tunnelToken.key required" .Values.secrets.external.paths.tunnelToken.key }}
      {{- if .Values.secrets.external.paths.tunnelToken.property }}
      property: {{ .Values.secrets.external.paths.tunnelToken.property }}
      {{- end }}
{{- end }}

{{- end }}