{{- if .Values.secrets.external.enabled }}
{{/*
External Secrets Integration
=============================
When enabled, this creates ExternalSecret resources instead of regular Secrets
The External Secrets Operator (must be pre-installed) watches these and:
1. Fetches actual secrets from external vault (Vault, AWS, GCP, Azure)
2. Creates regular Kubernetes Secrets automatically
3. Keeps them synced

PREREQUISITES:
- External Secrets Operator must be installed in cluster
- SecretStore must be configured (points to your vault)

USER EXPERIENCE:
Instead of: --set llm.apiKey=sk-...
User does:  --set secrets.external.enabled=true
           --set secrets.external.llmKeyPath=secret/data/consonant/llm-key
*/}}

---
# ExternalSecret for LLM API Key
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "consonant-relayer.llmSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "consonant-relayer.labels" . | nindent 4 }}
    app.kubernetes.io/component: external-secrets
spec:
  # How often to sync from external vault
  refreshInterval: {{ .Values.secrets.external.refreshInterval }}
  
  # Which SecretStore to use (must be pre-created by cluster admin)
  secretStoreRef:
    name: {{ .Values.secrets.external.secretStore }}
    kind: SecretStore
  
  # Target: the regular K8s Secret to create
  target:
    name: {{ include "consonant-relayer.llmSecretName" . }}
    creationPolicy: Owner
  
  # Data mapping: external vault path → K8s secret key
  data:
  - secretKey: apiKey
    remoteRef:
      key: {{ required "secrets.external.llmKeyPath is required when external secrets enabled" .Values.secrets.external.llmKeyPath }}
      {{- if .Values.secrets.external.llmKeyProperty }}
      property: {{ .Values.secrets.external.llmKeyProperty }}
      {{- end }}
  
  {{- if eq .Values.llm.provider "azureopenai" }}
  - secretKey: endpoint
    remoteRef:
      key: {{ .Values.secrets.external.azureEndpointPath }}
  
  - secretKey: deploymentName
    remoteRef:
      key: {{ .Values.secrets.external.azureDeploymentPath }}
  {{- end }}

{{- if .Values.cloudflare.enabled }}
---
# ExternalSecret for Cloudflare Tunnel Token
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "consonant-relayer.tunnelSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "consonant-relayer.labels" . | nindent 4 }}
    app.kubernetes.io/component: external-secrets
spec:
  refreshInterval: {{ .Values.secrets.external.refreshInterval }}
  
  secretStoreRef:
    name: {{ .Values.secrets.external.secretStore }}
    kind: SecretStore
  
  target:
    name: {{ include "consonant-relayer.tunnelSecretName" . }}
    creationPolicy: Owner
  
  data:
  - secretKey: token
    remoteRef:
      key: {{ required "secrets.external.tunnelTokenPath is required when external secrets enabled" .Values.secrets.external.tunnelTokenPath }}
      {{- if .Values.secrets.external.tunnelTokenProperty }}
      property: {{ .Values.secrets.external.tunnelTokenProperty }}
      {{- end }}
{{- end }}

{{- end }}