{{/*
NetworkPolicy - Pod-Level Network Isolation
============================================
ENABLED BY DEFAULT - Provides defense-in-depth security

Strategy:
- Ingress: Only authorized pods (KAgent) can send traffic
- Egress: Allow all external HTTPS, block private IPs
- Zero maintenance: No IP tracking required

This provides security benefits without operational burden.
*/}}

{{- if .Values.networkPolicy.enabled }}

{{/*
=============================================
RELAYER NETWORK POLICY
=============================================
Controls traffic to/from relayer pods
*/}}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "consonant-relayer.fullname" . }}-relayer
  namespace: {{ include "consonant-relayer.namespace" . }}
  labels:
    {{- include "consonant-relayer.labels" . | nindent 4 }}
    app.kubernetes.io/component: network-policy
  {{- with .Values.networkPolicy.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  podSelector:
    matchLabels:
      {{- include "consonant-relayer.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: relayer
  
  policyTypes:
    {{- toYaml .Values.networkPolicy.policyTypes | nindent 4 }}
  
  {{/*
  =============================================
  INGRESS RULES
  =============================================
  Restricts WHO can send traffic to relayer pods
  */}}
  ingress:
  {{- if .Values.networkPolicy.ingress.allowFromKAgent }}
  # Allow OTEL traffic from KAgent only
  - from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: kagent
    ports:
    - protocol: TCP
      port: {{ .Values.relayer.otel.port }}
  {{- end }}
  
  {{- if .Values.networkPolicy.ingress.allowHealthChecks }}
  # Allow health checks from within namespace
  - from:
    - podSelector: {}
    ports:
    - protocol: TCP
      port: {{ .Values.relayer.health.port }}
  {{- end }}
  
  {{- with .Values.networkPolicy.ingress.customRules }}
  # Custom ingress rules
  {{- toYaml . | nindent 2 }}
  {{- end }}
  
  {{/*
  =============================================
  EGRESS RULES
  =============================================
  Controls WHERE relayer pods can send traffic
  */}}
  egress:
  {{- if .Values.networkPolicy.egress.allowDNS }}
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system
    - podSelector:
        matchLabels:
          k8s-app: kube-dns
    ports:
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 53
  {{- end }}
  
  {{- if .Values.networkPolicy.egress.allowKubeAPI }}
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: default
    ports:
    - protocol: TCP
      port: 443
    - protocol: TCP
      port: 6443
  {{- end }}
  
  {{- if .Values.otelCollector.enabled }}
  - to:
    - podSelector:
        matchLabels:
          {{- include "consonant-relayer.selectorLabels" . | nindent 10 }}
          app.kubernetes.io/component: otel-collector
    ports:
    - protocol: TCP
      port: {{ .Values.otelCollector.ports.grpc }}
  {{- end }}
  
  {{- if .Values.networkPolicy.egress.allowHTTPS.enabled }}
  {{- if .Values.networkPolicy.egress.allowHTTPS.destinations }}
  {{- range .Values.networkPolicy.egress.allowHTTPS.destinations }}
  - to:
    - ipBlock:
        cidr: {{ . }}
    ports:
    - protocol: TCP
      port: 443
    - protocol: TCP
      port: 50051
  {{- end }}
  {{- else }}
  # Default: Allow all external HTTPS, block private ranges (recommended)
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
        # Block private IP ranges (prevents lateral movement)
        except:
        - 10.0.0.0/8       # RFC1918 Class A
        - 172.16.0.0/12    # RFC1918 Class B
        - 192.168.0.0/16   # RFC1918 Class C
        - 169.254.0.0/16   # Link-local
        - 127.0.0.0/8      # Loopback
        - 224.0.0.0/4      # Multicast
        - 240.0.0.0/4      # Reserved
    ports:
    - protocol: TCP
      port: 443
  {{- end }}
  {{- end }}
  
  {{- with .Values.networkPolicy.egress.customRules }}
  # Custom egress rules
  {{- toYaml . | nindent 2 }}
  {{- end }}

{{- if .Values.kagent.enabled }}
{{/*
=============================================
KAGENT NETWORK POLICY
=============================================
Controls traffic to/from KAgent pods
*/}}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "consonant-relayer.fullname" . }}-kagent
  namespace: {{ include "consonant-relayer.namespace" . }}
  labels:
    {{- include "consonant-relayer.labels" . | nindent 4 }}
    app.kubernetes.io/component: network-policy
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: kagent
  
  policyTypes:
  - Ingress
  - Egress
  
  # KAgent doesn't receive traffic (only sends telemetry)
  ingress: []
  
  egress:
  # DNS queries (required)
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system
    - podSelector:
        matchLabels:
          k8s-app: kube-dns
    ports:
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 53
  
  # OTEL telemetry to relayer (internal cluster communication)
  - to:
    - podSelector:
        matchLabels:
          {{- include "consonant-relayer.selectorLabels" . | nindent 10 }}
          app.kubernetes.io/component: relayer
    ports:
    - protocol: TCP
      port: {{ .Values.relayer.otel.port }}
  
  # Kubernetes API access (for agent operations)
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: default
    ports:
    - protocol: TCP
      port: 443
    - protocol: TCP
      port: 6443
  
  #
  # HTTPS for LLM API calls
  # =======================
  #
  # KAgent makes direct API calls to LLM providers (Anthropic, OpenAI, etc.)
  # Strategy: Allow all external HTTPS, block private IPs
  #
  # This provides:
  # ✅ Zero maintenance (no IP tracking)
  # ✅ Works with any LLM provider
  # ✅ Prevents lateral movement
  #
  {{- if .Values.networkPolicy.egress.allowHTTPS.enabled }}
  {{- if .Values.networkPolicy.egress.allowHTTPS.destinations }}
  # Custom destinations specified
  {{- range .Values.networkPolicy.egress.allowHTTPS.destinations }}
  - to:
    - ipBlock:
        cidr: {{ . }}
    ports:
    - protocol: TCP
      port: 443
  {{- end }}
  {{- else }}
  # Default: Allow all external HTTPS, block private ranges
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
        # Block private IP ranges
        except:
        - 10.0.0.0/8
        - 172.16.0.0/12
        - 192.168.0.0/16
        - 169.254.0.0/16
        - 127.0.0.0/8
    ports:
    - protocol: TCP
      port: 443
  {{- end }}
  {{- end }}

{{- end }}
{{- end }}