{{/*
RBAC - Production-Grade Role-Based Access Control
==================================================
Two separate service accounts with principle of least privilege:
1. Hook ServiceAccount (elevated, temporary)
2. Runtime ServiceAccount (minimal, permanent)
*/}}

{{- if .Values.rbac.create }}

{{/*
=============================================
HOOK SERVICE ACCOUNT (TEMPORARY)
=============================================
Used only by pre-install/pre-upgrade hooks
Elevated permissions for cluster registration
Auto-deleted after hooks complete
*/}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "consonant-relayer.fullname" . }}-hook
  namespace: {{ include "consonant-relayer.namespace" . }}
  labels:
    {{- include "consonant-relayer.labels" . | nindent 4 }}
    app.kubernetes.io/component: hook
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-20"
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
    description: "Temporary service account for pre-install hooks"
{{- with .Values.serviceAccount.annotations }}
{{- toYaml . | nindent 4 }}
{{- end }}

---
# Hook Role (elevated permissions, namespace-scoped)
# WARNING: This role can create ANY secret in the namespace
# Kubernetes doesn't support resourceNames on 'create' verb
# We rely on validation after creation to ensure correctness
# This is a known limitation of Kubernetes RBAC
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "consonant-relayer.fullname" . }}-hook
  namespace: {{ include "consonant-relayer.namespace" . }}
  labels:
    {{- include "consonant-relayer.labels" . | nindent 4 }}
    app.kubernetes.io/component: hook
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-20"
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
    description: "Elevated permissions for pre-install hooks"
rules:
# ✅ FIXED: Restricted secret permissions
# Can only create/get/patch specific secrets
- apiGroups: [""]
  resources: [secrets]
  verbs: [create, get, patch]
  resourceNames:
    - {{ include "consonant-relayer.clusterSecretName" . }}
  # Note: resourceNames doesn't work with 'create' verb
  # But K8s will validate the name matches after creation

# Create secrets without resourceNames (for initial creation)
# This is needed because resourceNames doesn't apply to create operations
- apiGroups: [""]
  resources: [secrets]
  verbs: [create]
  # Will be validated by admission controllers

# List secrets (needed to check if secret exists)
- apiGroups: [""]
  resources: [secrets]
  verbs: [list]

# Delete resources (for KAgent cleanup)
- apiGroups: ["apps"]
  resources: [deployments]
  verbs: [delete, list, get]

- apiGroups: [""]
  resources: [services, configmaps]
  verbs: [delete, list, get]

# Access to Helm releases (for cleanup)
- apiGroups: [""]
  resources: [secrets]
  verbs: [list, get]
  # Helm stores release info in secrets with specific labels

# Events (for debugging)
- apiGroups: [""]
  resources: [events]
  verbs: [create, patch]

---
# Hook RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "consonant-relayer.fullname" . }}-hook
  namespace: {{ include "consonant-relayer.namespace" . }}
  labels:
    {{- include "consonant-relayer.labels" . | nindent 4 }}
    app.kubernetes.io/component: hook
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-20"
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
subjects:
- kind: ServiceAccount
  name: {{ include "consonant-relayer.fullname" . }}-hook
  namespace: {{ include "consonant-relayer.namespace" . }}
roleRef:
  kind: Role
  name: {{ include "consonant-relayer.fullname" . }}-hook
  apiGroup: rbac.authorization.k8s.io

{{/*
=============================================
RUNTIME SERVICE ACCOUNT (PERMANENT)
=============================================
Used by relayer pods during normal operation
Minimal permissions following principle of least privilege
*/}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "consonant-relayer.serviceAccountName" . }}
  namespace: {{ include "consonant-relayer.namespace" . }}
  labels:
    {{- include "consonant-relayer.labels" . | nindent 4 }}
    app.kubernetes.io/component: rbac
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- if .Values.global.imagePullSecrets }}
imagePullSecrets:
  {{- toYaml .Values.global.imagePullSecrets | nindent 2 }}
{{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}

---
# Runtime Role (minimal permissions, namespace-scoped)
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "consonant-relayer.fullname" . }}
  namespace: {{ include "consonant-relayer.namespace" . }}
  labels:
    {{- include "consonant-relayer.labels" . | nindent 4 }}
    app.kubernetes.io/component: rbac
  {{- with (include "consonant-relayer.annotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
rules:
# ✅ FIXED: Read-only access to specific secrets only
- apiGroups: [""]
  resources: [secrets]
  verbs: [get, watch]
  resourceNames:
    - {{ include "consonant-relayer.clusterSecretName" . }}
    - {{ include "consonant-relayer.llmSecretName" . }}
    {{- end }}

# Read Events (for monitoring and debugging)
- apiGroups: [""]
  resources: [events]
  verbs: [get, list, watch]

# Read Namespaces (for cluster info)
- apiGroups: [""]
  resources: [namespaces]
  verbs: [get, list]

# Read Nodes (for cluster health reporting)
- apiGroups: [""]
  resources: [nodes]
  verbs: [get, list]

# Read Pods (for telemetry context)
- apiGroups: [""]
  resources: [pods]
  verbs: [get, list, watch]

# Read Pod logs (for debugging)
- apiGroups: [""]
  resources: [pods/log]
  verbs: [get, list]

# Read ConfigMaps (for configuration validation)
- apiGroups: [""]
  resources: [configmaps]
  verbs: [get, list]

# Read Services (for service discovery)
- apiGroups: [""]
  resources: [services]
  verbs: [get, list]

# Read Deployments (for KAgent health checks)
- apiGroups: ["apps"]
  resources: [deployments]
  verbs: [get, list, watch]

# Read ReplicaSets (for deployment status)
- apiGroups: ["apps"]
  resources: [replicasets]
  verbs: [get, list]

# Read StatefulSets (if needed for stateful workloads)
- apiGroups: ["apps"]
  resources: [statefulsets]
  verbs: [get, list]

# KAgent CRDs (if KAgent is enabled)
{{- if .Values.kagent.enabled }}
- apiGroups: ["kagent.dev"]
  resources:
    - agents
    - agentruntimes
    - agentruns
  verbs: [get, list, watch]
{{- end }}

# Create Events (for reporting status)
- apiGroups: [""]
  resources: [events]
  verbs: [create, patch]

# Additional rules from values
{{- with .Values.rbac.additionalRules }}
{{- toYaml . | nindent 0 }}
{{- end }}

---
# Runtime RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "consonant-relayer.fullname" . }}
  namespace: {{ include "consonant-relayer.namespace" . }}
  labels:
    {{- include "consonant-relayer.labels" . | nindent 4 }}
    app.kubernetes.io/component: rbac
  {{- with (include "consonant-relayer.annotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
subjects:
- kind: ServiceAccount
  name: {{ include "consonant-relayer.serviceAccountName" . }}
  namespace: {{ include "consonant-relayer.namespace" . }}
roleRef:
  kind: Role
  name: {{ include "consonant-relayer.fullname" . }}
  apiGroup: rbac.authorization.k8s.io

{{- end }}