{{/*
Secrets - Production-Grade Secret Management
============================================
Supports both external secrets (recommended) and Kubernetes secrets
External secrets use External Secrets Operator
*/}}

{{/* Run validations */}}
{{- include "consonant-relayer.validate.secrets" . }}

{{- if eq .Values.secrets.mode "kubernetes" }}
{{- if not .Values.secrets.external.enabled }}
{{/*
=============================================
KUBERNETES NATIVE SECRETS (FALLBACK)
=============================================
Only used when external secrets are disabled
WARNING: These are base64 encoded, NOT encrypted
Requires etcd encryption at cluster level
*/}}

---
# LLM API Key Secret
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "consonant-relayer.llmSecretName" . }}
  namespace: {{ include "consonant-relayer.namespace" . }}
  labels:
    {{- include "consonant-relayer.labels" . | nindent 4 }}
    app.kubernetes.io/component: configuration
  {{- with (include "consonant-relayer.annotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  apiKey: {{ required "secrets.kubernetes.llmApiKey is required when mode=kubernetes" .Values.secrets.kubernetes.llmApiKey | quote }}
  
  {{- if eq .Values.llm.provider "azureopenai" }}
  endpoint: {{ required "secrets.kubernetes.azureEndpoint required for Azure OpenAI" .Values.secrets.kubernetes.azureEndpoint | quote }}
  deploymentName: {{ required "secrets.kubernetes.azureDeploymentName required for Azure OpenAI" .Values.secrets.kubernetes.azureDeploymentName | quote }}
  {{- end }}
  
  {{- if eq .Values.llm.provider "ollama" }}
  baseUrl: {{ .Values.llm.ollama.baseURL | quote }}
  {{- end }}



{{- end }}
{{- end }}

{{/*
=============================================
CLUSTER CREDENTIALS SECRET
=============================================
NEVER created here - always created by pre-install hook
This secret contains dynamic credentials from backend
*/}}