# {{/*
# Secrets - Sensitive Configuration
# ==================================
# Contains secrets needed by relayer and KAgent:
# 1. LLM API key
# 2. Cloudflare tunnel token (if using tunnel)

# SECURITY NOTES:
# - Secrets are base64 encoded by K8s (not encrypted at rest by default)
# - Use external secret management for production (Sealed Secrets, External Secrets Operator, Vault)
# - Helm values containing secrets should never be committed to git
# - Use --set flags or separate values files with restricted permissions
# */}}

# {{/* Run validation before creating any secrets */}}
# {{- include "consonant-relayer.validateValues" . }}

# {{/*
# =============================================
# Secret 1: LLM API Key
# =============================================
# Used by KAgent to authenticate with LLM provider
# Referenced by KAgent via kagent.providers.*.apiKeySecretRef
# */}}
# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: {{ include "consonant-relayer.llmSecretName" . }}
#   namespace: {{ .Release.Namespace }}
#   labels:
#     {{- include "consonant-relayer.labels" . | nindent 4 }}
#     app.kubernetes.io/component: configuration
#   {{- with (include "consonant-relayer.annotations" .) }}
#   annotations:
#     {{- . | nindent 4 }}
#   {{- end }}
# type: Opaque
# stringData:
#   # API key for LLM provider
#   # stringData automatically base64 encodes the value
#   apiKey: {{ required "llm.apiKey is required" .Values.llm.apiKey | quote }}
  
#   {{- if eq .Values.llm.provider "azureopenai" }}
#   # Azure OpenAI specific
#   endpoint: {{ required "llm.azure.endpoint is required for Azure OpenAI" .Values.llm.azure.endpoint | quote }}
#   deploymentName: {{ required "llm.azure.deploymentName is required for Azure OpenAI" .Values.llm.azure.deploymentName | quote }}
#   {{- end }}
  
#   {{- if eq .Values.llm.provider "ollama" }}
#   # Ollama specific
#   baseUrl: {{ .Values.llm.ollama.baseUrl | quote }}
#   {{- end }}

# {{/*
# =============================================
# Secret 2: Cloudflare Tunnel Token
# =============================================
# Only created if Cloudflare tunnel is enabled
# Used by cloudflared sidecar to authenticate tunnel
# */}}
# {{- if .Values.cloudflare.enabled }}
# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: {{ include "consonant-relayer.tunnelSecretName" . }}
#   namespace: {{ .Release.Namespace }}
#   labels:
#     {{- include "consonant-relayer.labels" . | nindent 4 }}
#     app.kubernetes.io/component: tunnel
#   {{- with (include "consonant-relayer.annotations" .) }}
#   annotations:
#     {{- . | nindent 4 }}
#   {{- end }}
# type: Opaque
# stringData:
#   # Cloudflare tunnel token
#   # Get from: Cloudflare Dashboard → Zero Trust → Access → Tunnels
#   # Format: eyJhIjoiY...
#   token: {{ required "cloudflare.tunnelToken is required when cloudflare.enabled is true" .Values.cloudflare.tunnelToken | quote }}
# {{- end }}

# {{/*
# =============================================
# Secret 3: Cluster Credentials
# =============================================
# NOT CREATED HERE - created by pre-install hook
# This secret contains:
# - clusterId: unique cluster identifier from backend
# - clusterToken: authentication token for backend
# - clusterName: human-readable cluster name

# The pre-install hook Job calls backend API and stores response here
# Relayer reads this secret to authenticate with backend

# Secret name: {{ include "consonant-relayer.clusterSecretName" . }}
# */}}



{{- include "consonant-relayer.validateValues" . }}

{{- if not .Values.secrets.external.enabled }}
{{/*
Regular Kubernetes Secrets
===========================
Only created when external secrets are DISABLED
When external secrets are enabled, ExternalSecret resources create these automatically
*/}}

---
# LLM API Key Secret
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "consonant-relayer.llmSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "consonant-relayer.labels" . | nindent 4 }}
    app.kubernetes.io/component: configuration
  {{- with (include "consonant-relayer.annotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  apiKey: {{ required "llm.apiKey is required when secrets.external.enabled is false" .Values.llm.apiKey | quote }}
  
  {{- if eq .Values.llm.provider "azureopenai" }}
  endpoint: {{ required "llm.azure.endpoint is required for Azure OpenAI" .Values.llm.azure.endpoint | quote }}
  deploymentName: {{ required "llm.azure.deploymentName is required for Azure OpenAI" .Values.llm.azure.deploymentName | quote }}
  {{- end }}
  
  {{- if eq .Values.llm.provider "ollama" }}
  baseUrl: {{ .Values.llm.ollama.baseUrl | quote }}
  {{- end }}

{{- if .Values.cloudflare.enabled }}
---
# Cloudflare Tunnel Token Secret
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "consonant-relayer.tunnelSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "consonant-relayer.labels" . | nindent 4 }}
    app.kubernetes.io/component: tunnel
  {{- with (include "consonant-relayer.annotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  token: {{ required "cloudflare.tunnelToken is required when cloudflare.enabled is true and secrets.external.enabled is false" .Values.cloudflare.tunnelToken | quote }}
{{- end }}

{{- end }}

{{/*
Cluster Credentials Secret
===========================
ALWAYS created by pre-install hook, never by external secrets
This is dynamic - backend generates it during cluster registration
*/}}