{{/*
ServiceMonitor - Prometheus Operator Integration
================================================
Configures Prometheus to scrape metrics from relayer pods
Requires Prometheus Operator to be installed
*/}}

{{- if .Values.serviceMonitor.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "consonant-relayer.fullname" . }}
  {{- if .Values.serviceMonitor.namespace }}
  namespace: {{ .Values.serviceMonitor.namespace }}
  {{- else }}
  namespace: {{ include "consonant-relayer.namespace" . }}
  {{- end }}
  labels:
    {{- include "consonant-relayer.labels" . | nindent 4 }}
    app.kubernetes.io/component: monitoring
    {{- with .Values.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with (include "consonant-relayer.annotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
spec:
  # Select the service to scrape
  selector:
    matchLabels:
      {{- include "consonant-relayer.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: relayer
  
  # Namespace selector
  namespaceSelector:
    matchNames:
      - {{ include "consonant-relayer.namespace" . }}
  
  # Endpoint configuration
  endpoints:
  - port: health
    path: {{ .Values.serviceMonitor.path }}
    interval: {{ .Values.serviceMonitor.interval }}
    scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
    scheme: http
    
    {{- with .Values.serviceMonitor.metricRelabelings }}
    metricRelabelings:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    
    {{- with .Values.serviceMonitor.relabelings }}
    relabelings:
      {{- toYaml . | nindent 6 }}
    {{- end }}
  
{{- end }}